/*
 Highmaps JS v5.0.14 (2019-01-17)

 (c) 2009-2017 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(t){"object"===typeof module&&module.exports?module.exports=t:t(Highcharts)})(function(t){(function(h){var q=h.win.document,c=h.each,r=h.objectEach,f=h.pick,m=h.inArray,u=h.isNumber,x=h.splat,n,k=function(a,b){this.init(a,b)};h.extend(k.prototype,{init:function(a,b){this.options=a;this.chartOptions=b;this.columns=a.columns||this.rowsToColumns(a.rows)||[];this.firstRowAsNames=f(a.firstRowAsNames,!0);this.decimalRegex=a.decimalPoint&&new RegExp("^(-?[0-9]+)"+a.decimalPoint+"([0-9]+)$");this.rawColumns=
[];this.columns.length?this.dataFound():(this.parseCSV(),this.parseTable(),this.parseGoogleSpreadsheet())},getColumnDistribution:function(){var a=this.chartOptions,b=this.options,g=[],p=function(a){return(h.seriesTypes[a||"line"].prototype.pointArrayMap||[0]).length},e=a&&a.chart&&a.chart.type,d=[],f=[],w=0,l;c(a&&a.series||[],function(a){d.push(p(a.type||e))});c(b&&b.seriesMapping||[],function(a){g.push(a.x||0)});0===g.length&&g.push(0);c(b&&b.seriesMapping||[],function(b){var g=new n,c=d[w]||p(e),
v=h.seriesTypes[((a&&a.series||[])[w]||{}).type||e||"line"].prototype.pointArrayMap||["y"];g.addColumnReader(b.x,"x");r(b,function(a,b){"x"!==b&&g.addColumnReader(a,b)});for(l=0;l<c;l++)g.hasReader(v[l])||g.addColumnReader(void 0,v[l]);f.push(g);w++});b=h.seriesTypes[e||"line"].prototype.pointArrayMap;void 0===b&&(b=["y"]);this.valueCount={global:p(e),xColumns:g,individual:d,seriesBuilders:f,globalPointArrayMap:b}},dataFound:function(){this.options.switchRowsAndColumns&&(this.columns=this.rowsToColumns(this.columns));
this.getColumnDistribution();this.parseTypes();!1!==this.parsed()&&this.complete()},parseCSV:function(){var a=this,b=this.options,g=b.csv,p=this.columns,e=b.startRow||0,d=b.endRow||Number.MAX_VALUE,f=b.startColumn||0,w=b.endColumn||Number.MAX_VALUE,l,h,n=0;g&&(h=g.replace(/\r\n/g,"\n").replace(/\r/g,"\n").split(b.lineDelimiter||"\n"),l=b.itemDelimiter||(-1!==g.indexOf("\t")?"\t":","),c(h,function(b,g){var v=a.trim(b),h=0===v.indexOf("#");g>=e&&g<=d&&!h&&""!==v&&(b=b.split(l),c(b,function(a,b){b>=
f&&b<=w&&(p[b-f]||(p[b-f]=[]),p[b-f][n]=a)}),n+=1)}),this.dataFound())},parseTable:function(){var a=this.options,b=a.table,g=this.columns,p=a.startRow||0,e=a.endRow||Number.MAX_VALUE,d=a.startColumn||0,f=a.endColumn||Number.MAX_VALUE;b&&("string"===typeof b&&(b=q.getElementById(b)),c(b.getElementsByTagName("tr"),function(a,b){b>=p&&b<=e&&c(a.children,function(a,e){("TD"===a.tagName||"TH"===a.tagName)&&e>=d&&e<=f&&(g[e-d]||(g[e-d]=[]),g[e-d][b-p]=a.innerHTML)})}),this.dataFound())},parseGoogleSpreadsheet:function(){var a=
this,b=this.options,g=b.googleSpreadsheetKey,p=this.columns,e=b.startRow||0,d=b.endRow||Number.MAX_VALUE,f=b.startColumn||0,w=b.endColumn||Number.MAX_VALUE,l,h;g&&jQuery.ajax({dataType:"json",url:"https://spreadsheets.google.com/feeds/cells/"+g+"/"+(b.googleSpreadsheetWorksheet||"od6")+"/public/values?alt\x3djson-in-script\x26callback\x3d?",error:b.error,success:function(b){b=b.feed.entry;var g,n=b.length,v=0,m=0,k;for(k=0;k<n;k++)g=b[k],v=Math.max(v,g.gs$cell.col),m=Math.max(m,g.gs$cell.row);for(k=
0;k<v;k++)k>=f&&k<=w&&(p[k-f]=[],p[k-f].length=Math.min(m,d-e));for(k=0;k<n;k++)g=b[k],l=g.gs$cell.row-1,h=g.gs$cell.col-1,h>=f&&h<=w&&l>=e&&l<=d&&(p[h-f][l-e]=g.content.$t);c(p,function(a){for(k=0;k<a.length;k++)void 0===a[k]&&(a[k]=null)});a.dataFound()}})},trim:function(a,b){"string"===typeof a&&(a=a.replace(/^\s+|\s+$/g,""),b&&/^[0-9\s]+$/.test(a)&&(a=a.replace(/\s/g,"")),this.decimalRegex&&(a=a.replace(this.decimalRegex,"$1.$2")));return a},parseTypes:function(){for(var a=this.columns,b=a.length;b--;)this.parseColumn(a[b],
b)},parseColumn:function(a,b){var g=this.rawColumns,p=this.columns,e=a.length,d,c,f,l,k=this.firstRowAsNames,h=-1!==m(b,this.valueCount.xColumns),n=[],r=this.chartOptions,q,t=(this.options.columnTypes||[])[b],r=h&&(r&&r.xAxis&&"category"===x(r.xAxis)[0].type||"string"===t);for(g[b]||(g[b]=[]);e--;)d=n[e]||a[e],f=this.trim(d),l=this.trim(d,!0),c=parseFloat(l),void 0===g[b][e]&&(g[b][e]=f),r||0===e&&k?a[e]=f:+l===c?(a[e]=c,31536E6<c&&"float"!==t?a.isDatetime=!0:a.isNumeric=!0,void 0!==a[e+1]&&(q=c>
a[e+1])):(c=this.parseDate(d),h&&u(c)&&"float"!==t?(n[e]=d,a[e]=c,a.isDatetime=!0,void 0!==a[e+1]&&(d=c>a[e+1],d!==q&&void 0!==q&&(this.alternativeFormat?(this.dateFormat=this.alternativeFormat,e=a.length,this.alternativeFormat=this.dateFormats[this.dateFormat].alternative):a.unsorted=!0),q=d)):(a[e]=""===f?null:f,0!==e&&(a.isDatetime||a.isNumeric)&&(a.mixed=!0)));h&&a.mixed&&(p[b]=g[b]);if(h&&q&&this.options.sort)for(b=0;b<p.length;b++)p[b].reverse(),k&&p[b].unshift(p[b].pop())},dateFormats:{"YYYY-mm-dd":{regex:/^([0-9]{4})[\-\/\.]([0-9]{2})[\-\/\.]([0-9]{2})$/,
parser:function(a){return Date.UTC(+a[1],a[2]-1,+a[3])}},"dd/mm/YYYY":{regex:/^([0-9]{1,2})[\-\/\.]([0-9]{1,2})[\-\/\.]([0-9]{4})$/,parser:function(a){return Date.UTC(+a[3],a[2]-1,+a[1])},alternative:"mm/dd/YYYY"},"mm/dd/YYYY":{regex:/^([0-9]{1,2})[\-\/\.]([0-9]{1,2})[\-\/\.]([0-9]{4})$/,parser:function(a){return Date.UTC(+a[3],a[1]-1,+a[2])}},"dd/mm/YY":{regex:/^([0-9]{1,2})[\-\/\.]([0-9]{1,2})[\-\/\.]([0-9]{2})$/,parser:function(a){return Date.UTC(+a[3]+2E3,a[2]-1,+a[1])},alternative:"mm/dd/YY"},
"mm/dd/YY":{regex:/^([0-9]{1,2})[\-\/\.]([0-9]{1,2})[\-\/\.]([0-9]{2})$/,parser:function(a){return Date.UTC(+a[3]+2E3,a[1]-1,+a[2])}}},parseDate:function(a){var b=this.options.parseDate,g,c,e=this.options.dateFormat||this.dateFormat,d;if(b)g=b(a);else if("string"===typeof a){if(e)b=this.dateFormats[e],(d=a.match(b.regex))&&(g=b.parser(d));else for(c in this.dateFormats)if(b=this.dateFormats[c],d=a.match(b.regex)){this.dateFormat=c;this.alternativeFormat=b.alternative;g=b.parser(d);break}d||(d=Date.parse(a),
"object"===typeof d&&null!==d&&d.getTime?g=d.getTime()-6E4*d.getTimezoneOffset():u(d)&&(g=d-6E4*(new Date(d)).getTimezoneOffset()))}return g},rowsToColumns:function(a){var b,g,c,e,d;if(a)for(d=[],g=a.length,b=0;b<g;b++)for(e=a[b].length,c=0;c<e;c++)d[c]||(d[c]=[]),d[c][b]=a[b][c];return d},parsed:function(){if(this.options.parsed)return this.options.parsed.call(this,this.columns)},getFreeIndexes:function(a,b){var g,c=[],e=[],d;for(g=0;g<a;g+=1)c.push(!0);for(a=0;a<b.length;a+=1)for(d=b[a].getReferencedColumnIndexes(),
g=0;g<d.length;g+=1)c[d[g]]=!1;for(g=0;g<c.length;g+=1)c[g]&&e.push(g);return e},complete:function(){var a=this.columns,b,g=this.options,c,e,d,f,k=[],l;if(g.complete||g.afterComplete){for(d=0;d<a.length;d++)this.firstRowAsNames&&(a[d].name=a[d].shift());c=[];e=this.getFreeIndexes(a.length,this.valueCount.seriesBuilders);for(d=0;d<this.valueCount.seriesBuilders.length;d++)l=this.valueCount.seriesBuilders[d],l.populateColumns(e)&&k.push(l);for(;0<e.length;){l=new n;l.addColumnReader(0,"x");d=m(0,e);
-1!==d&&e.splice(d,1);for(d=0;d<this.valueCount.global;d++)l.addColumnReader(void 0,this.valueCount.globalPointArrayMap[d]);l.populateColumns(e)&&k.push(l)}0<k.length&&0<k[0].readers.length&&(l=a[k[0].readers[0].columnIndex],void 0!==l&&(l.isDatetime?b="datetime":l.isNumeric||(b="category")));if("category"===b)for(d=0;d<k.length;d++)for(l=k[d],e=0;e<l.readers.length;e++)"x"===l.readers[e].configName&&(l.readers[e].configName="name");for(d=0;d<k.length;d++){l=k[d];e=[];for(f=0;f<a[0].length;f++)e[f]=
l.read(a,f);c[d]={data:e};l.name&&(c[d].name=l.name);"category"===b&&(c[d].turboThreshold=0)}a={series:c};b&&(a.xAxis={type:b},"category"===b&&(a.xAxis.uniqueNames=!1));g.complete&&g.complete(a);g.afterComplete&&g.afterComplete(a)}}});h.Data=k;h.data=function(a,b){return new k(a,b)};h.wrap(h.Chart.prototype,"init",function(a,b,c){var g=this;b&&b.data?h.data(h.extend(b.data,{afterComplete:function(e){var d,f;if(b.hasOwnProperty("series"))if("object"===typeof b.series)for(d=Math.max(b.series.length,
e.series.length);d--;)f=b.series[d]||{},b.series[d]=h.merge(f,e.series[d]);else delete b.series;b=h.merge(e,b);a.call(g,b,c)}}),b):a.call(g,b,c)});n=function(){this.readers=[];this.pointIsArray=!0};n.prototype.populateColumns=function(a){var b=!0;c(this.readers,function(b){void 0===b.columnIndex&&(b.columnIndex=a.shift())});c(this.readers,function(a){void 0===a.columnIndex&&(b=!1)});return b};n.prototype.read=function(a,b){var g=this.pointIsArray,f=g?[]:{},e;c(this.readers,function(c){var e=a[c.columnIndex][b];
g?f.push(e):f[c.configName]=e});void 0===this.name&&2<=this.readers.length&&(e=this.getReferencedColumnIndexes(),2<=e.length&&(e.shift(),e.sort(),this.name=a[e.shift()].name));return f};n.prototype.addColumnReader=function(a,b){this.readers.push({columnIndex:a,configName:b});"x"!==b&&"y"!==b&&void 0!==b&&(this.pointIsArray=!1)};n.prototype.getReferencedColumnIndexes=function(){var a,b=[],c;for(a=0;a<this.readers.length;a+=1)c=this.readers[a],void 0!==c.columnIndex&&b.push(c.columnIndex);return b};
n.prototype.hasReader=function(a){var b,c;for(b=0;b<this.readers.length;b+=1)if(c=this.readers[b],c.configName===a)return!0}})(t);(function(h){var q=h.each;h.wrap(h.Data.prototype,"init",function(c,h){c.call(this,h);h.svg&&this.loadSVG()});h.extend(h.Data.prototype,{pathToArray:function(c,h){var f=0,m=0,r,q,n=[0,0],k=[0,0],a,b,g=function(a,b){return[b.a*a[0]+b.c*a[1]+b.e,b.b*a[0]+b.d*a[1]+b.f]};c=c.replace(/[0-9]+e-?[0-9]+/g,function(a){return+a}).replace(/([A-Za-z])/g," $1 ").replace(/-/g," -").replace(/^\s*/,
"").replace(/\s*$/,"").replace(/\s+/g," ").split(/[ ,]+/);if(1===c.length)return[];for(f=0;f<c.length;f++)if(r=/[a-zA-Z]/.test(c[f])){b=c[f];q=2;if("c"===b||"C"===b)q=6;"m"===b?k=[parseFloat(c[f+1])+k[0],parseFloat(c[f+2])+k[1]]:"M"===b&&(k=[parseFloat(c[f+1]),parseFloat(c[f+2])]);if("m"===b||"l"===b||"c"===b)c[f]=b.toUpperCase(),a=!0;else if("M"===b||"L"===b||"C"===b)a=!1;else if("h"===b)a=!0,c[f]="L",c.splice(f+2,0,0);else if("v"===b)a=!0,c[f]="L",c.splice(f+1,0,0);else if("s"===b)a=!0,c[f]="L",
c.splice(f+1,2);else if("S"===b)a=!1,c[f]="L",c.splice(f+1,2);else if("H"===b||"h"===b)a=!1,c[f]="L",c.splice(f+2,0,n[1]);else if("V"===b||"v"===b)a=!1,c[f]="L",c.splice(f+1,0,n[0]);else if("z"===b||"Z"===b)n=k}else c[f]=parseFloat(c[f]),a&&(c[f]+=n[m%2]),1===m%2&&h&&(!a||"m"===b&&3>f)&&(r=g([c[f-1],c[f]],h),c[f-1]=r[0],c[f]=r[1]),m===q-1?(n=[c[f-1],c[f]],m=0):m+=1;"number"===typeof c[0]&&4<=c.length&&(c.unshift("M"),c.splice(3,0,"L"));return c},pathToString:function(c){q(c,function(c){var f=c.path,
f=f.join(","),f=f.replace(/,?([a-zA-Z]),?/g,"$1");c.path=f});return c},roundPaths:function(c,r){var f=h.seriesTypes.map.prototype,m,u;m={xAxis:{translate:h.Axis.prototype.translate,options:{},minPixelPadding:0},yAxis:{translate:h.Axis.prototype.translate,options:{},minPixelPadding:0}};f.getBox.call(m,c);u=Math.max(m.maxX-m.minX,m.maxY-m.minY);r=r||1E3;u=r/u;m.xAxis.transA=m.yAxis.transA=u;m.xAxis.len=m.yAxis.len=r;m.xAxis.min=m.minX;m.yAxis.min=(m.minY+r)/u;q(c,function(c){var h,k;c.path=k=f.translatePath.call(m,
c.path,!0);for(h=k.length;h--;)"number"===typeof k[h]&&(k[h]=Math.round(k[h]));delete c._foundBox});return c},loadSVG:function(){function c(a){return Array.prototype.slice.call(a.getElementsByTagName("path")).concat(Array.prototype.slice.call(a.getElementsByTagName("polygon"))).concat(Array.prototype.slice.call(a.getElementsByTagName("rect")))}function h(a){if("path"===a.nodeName)return a.getAttribute("d");if("polygon"===a.nodeName)return a.getAttribute("points");if("rect"===a.nodeName){var b=+a.getAttribute("x"),
c=+a.getAttribute("y"),f=+a.getAttribute("width");a=+a.getAttribute("height");return[b,c,b+f,c,b+f,c+a,b,c+a,b,c].join(" ")}}function f(a){a=a.getCTM();if(!isNaN(a.f))return a}function m(a){var b=a.getElementsByTagName("desc");return(b=b[0]&&b[0].getElementsByTagName("name"))&&b[0]&&b[0].innerText||a.getAttribute("inkscape:label")||a.getAttribute("id")||a.getAttribute("class")}function u(a){return!/fill[\s]?\:[\s]?none/.test(a.getAttribute("style"))&&"none"!==a.getAttribute("fill")}function t(a){var b=
[],g,p,e,d,r;n.$frame=n.$frame||$("\x3cdiv\x3e").css({position:"absolute",top:"-9999em"}).appendTo($(document.body));n.$frame.html(a);a=$("svg",n.$frame)[0];a.removeAttribute("viewBox");p=c(a);q(["defs","clipPath"],function(b){q(a.getElementsByTagName(b),function(a){q(a.getElementsByTagName("path"),function(a){a.skip=!0})})});q(p,function(a,b){if(!a.skip){var c=[];0<b&&a.parentNode!==g&&(r=!0);for(g=a.parentNode;a;)c.push(a),a=a.parentNode;c.reverse();if(e)for(a=0;a<e.length;a++)e[a]!==c[a]&&(e=e.slice(0,
a));else e=c}});d=e[e.length-1];r&&q(d.getElementsByTagName("g"),function(a){var d=[],e;q(c(a),function(a){a.skip||(d=d.concat(n.pathToArray(h(a),f(a))),u(a)&&(e=!0),a.skip=!0)});b.push({name:m(a),path:d,hasFill:e})});q(p,function(a){a.skip||b.push({name:m(a),path:n.pathToArray(h(a),f(a)),hasFill:u(a)})});n.roundPaths(b);k.complete({series:[{data:b}]})}var n=this,k=this.options;-1!==k.svg.indexOf("\x3csvg")?t(k.svg):jQuery.ajax({url:k.svg,dataType:"text",success:t})}})})(t)});